name: f0Effects
version: 1.3.0
main: me.f0rant.f0effects.f0Effects
api-version: '1.21'
authors: [f0rant]
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  f0effects:
    description: Main command for GUI and Admin management
    aliases: [killeffects, ke, keffect, efectsfromkill, efekty, effects, f0ef]