name: f0Effects
version: 1.0.0
main: me.f0rant.f0effects.f0Effects
api-version: '1.21'
authors: [f0rant]
depend: [Vault]

commands:
  efekty:
    description: Opens the kill effect menu
    aliases: [effects]

  f0ef:
    description: Admin command for managing effects
    permission: f0effects.admin
    permission-message: "&#FF0000You do not have permission to use this command!"